### ISSUE TITLE
Release for Melodic

### ISSUE THREAD

**Issue by kmhallen** [ros-drivers/joystick_drivers#119]
It looks like all of the dependencies are available in Melodic, so it would be great to get this released. Thanks in advance!

**Comment by gvallicrosa** [comment]
I just tried it in a virtual machine with ubuntu 18.04 and ROS melodic and compiled fine.

**Comment by JWhitleyAStuff** [comment]
Release 1.12.0 is pending for Indigo, Kinetic, Lunar, and Melodic. See #118 for updates.

**Comment by kmhallen** [comment]
Thanks!

**Comment by roehling** [comment]
The release 1.12.0 has been published for all ROS versions except Melodic, which is the only ROS version with no released `joystick_drivers` whatsoever. Can someone with more insight than me figure out why the Melodic release is missing?

**Comment by kmhallen** [comment]
It has been released into Melodic and it is present in the  ```building``` and ```testing``` repos. It will make it to ```main``` when the person at OSRF decides to sync all package to ```main```.
http://repositories.ros.org/status_page/ros_melodic_default.html?q=joy

The link below explains how to pull binaries from repos other than main/public:
http://wiki.ros.org/ShadowRepository

**Comment by roehling** [comment]
Thanks, I am aware of the shadow repository; however, I'm planning to migrate several departments to the new ROS LTS, and I'd rather have them not tinker around with release candidates. 

I was just wondering if there might be a particular reason for the missing release besides "we didn't feel like syncing it, man". :wink:
