### ISSUE TITLE
How to include State.h?

### ISSUE THREAD

**Issue by Mozyanari** [ros-drivers/joystick_drivers#131]
I want to use wiimote::State message type

So, I write 
#include <wiimote/State.h>
in my program

but, error message
fatal error: wiimote/State.h: No such file or directory

I can't understand that why this message happen
How to include State.h?

**Comment by JWhitleyAStuff** [comment]
@Mozyanari - State.h is a generated file for the message State.msg. In order to generate this message, make sure your ROS package has a dependency on the `wiimote` package in both CMakeLists.txt and package.xml.

**Comment by Mozyanari** [comment]
Thank you!
