### ISSUE TITLE
$ rosrun joy joy_node and it throws a error Segmentation fault (core dumped)  Can anyone help me out???

### ISSUE THREAD

**Issue by stevensu1838** [ros-drivers/joystick_drivers#133]
ROS kinetic Ubuntu 16.04 Xbox360 wired controller
Followed tutorial: http://wiki.ros.org/joy/Tutorials/ConfiguringALinuxJoystick
```

user@mech1349:~$ rosparam set joy_node/dev "/dev/input/js0"
user@mech1349:~$ rosrun joy joy_node
Segmentation fault (core dumped)
```

Can anyone help me out???

**Comment by JWhitleyAStuff** [comment]
Which version of ROS are you using? Which version of joystick_drivers? What OS? Which joystick?

**Comment by JWhitleyAStuff** [comment]
See #129.
