### ISSUE TITLE
Couldn't open joystick force feedback!

### ISSUE THREAD

**Issue by stevensu1838** [ros-drivers/joystick_drivers#134]
ROS kinetic Ubuntu 16.04 Xbox360 wired controller
Followed tutorial: http://wiki.ros.org/joy/Tutorials/ConfiguringALinuxJoystick

```
user@mech1349:~/catkin_ws$ rosrun joy joy_node
[ERROR] [1541708274.096842680]: Couldn't open joystick force feedback!
[ INFO] [1541708274.096904049]: Opened joystick: /dev/input/js0. deadzone_: 0.050000.
```

**Comment by JWhitleyAStuff** [comment]
Which version of ROS are you using? Which version of joystick_drivers? What OS? Which joystick?

Force feedback may not be supported on your joystick.

**Comment by pravin382** [comment]
I am also getting the same error. This joystick was working properly before 4 months. 

Some information requested above
ROS version: Kinetic
Joystick_driver: kinetic
OS: Ubuntu 16.04
joystick: Xbox360 wired controller, logitech wireless controller

**Comment by ArghyaChatterjee** [comment]
Same error here. Same configuration and same error. Somebody please help.

**Comment by JWhitleyAStuff** [comment]
@pravin382 / @ArghyaChatterjee - The error is non-fatal - i.e., it can be ignored. It's just telling you that it failed to enable force-feedback because it is not available on your controller. Everything else should work fine.

**Comment by ArghyaChatterjee** [comment]
Thanks @JWhitleyAStuff. I also found the same thing after using it. It's working and I have ignored the error.
