### ISSUE TITLE
F710 issue on jetson xavier with ubuntu 18.04 and ros melodic 

### ISSUE THREAD

**Issue by lsztyber** [ros-drivers/joystick_drivers#138]
On Nvidia Jetson AGX Xavier with Ubuntu 18.04 and ROS melodic joy_node doesn't publish anything for Logitech F710 (direct input mode) despite it claims to detect joystic at /dev/inputs/js0. Jstest run for /dev/inputs/js0 also doesn't notice any buttons being pressed. The same gamepad connected to a laptop with Ubuntu 16.04 and ROS kinetic works well.

**Comment by JWhitleyAStuff** [comment]
Unfortunately, this is out of scope for this driver since, as you have mentioned, other tools do not see the button presses either. This is likely due to a bug in the driver supporting the USB ports on the Jetson. Sorry I can't be of more help.
