### ISSUE TITLE
Add pairing/unpairing sound.  (ros-pkg ticket #3782)

### ISSUE THREAD

**Issue by wjwwood** [ros-drivers/joystick_drivers#14]
Useful given that the joystick will auto-unpair.

trac data:
- Owner: **blaise**
- Reporter: **blaise**
- Reported at: **Mon Feb  1 13:36:04 2010**
- URL: https://code.ros.org/trac/ros-pkg/joystick_drivers/ticket/3782

**Comment by JWhitleyAStuff** [comment]
Already addressed by a920f97.
