### ISSUE TITLE
steering wheel logitech g29  with ubutnu 16.04

### ISSUE THREAD

**Issue by TZVIh** [ros-drivers/joystick_drivers#140]
Hi,
I want to buy wheel and pedals (Logitech G29).
Will it work with joy node?
Thanks!

**Comment by JWhitleyAStuff** [comment]
Yes, the Logitech G29 has been confirmed to work correctly with this driver.

**Comment by TZVIh** [comment]
Thanks! 
I have some problem. I got msg only if the value of the pedal/wheel is changed.
 what should I do to change it?

**Comment by JWhitleyAStuff** [comment]
@TZVIh - If you want to receive the message regularly instead of only when a button is pressed or when the pedals are moved, set the _autorepeat_rate_ parameter to your desired repeat rate. For more information, see http://wiki.ros.org/joy
