### ISSUE TITLE
Configuring ps3joy through USB without bluetooth?

### ISSUE THREAD

**Issue by pranjalipadghan** [ros-drivers/joystick_drivers#141]

**Comment by JWhitleyAStuff** [comment]
It's been almost a year since this was asked (sorry it wasn't answered sooner). Please re-open if you are still looking for an answer.

**Comment by mikaelarguedas** [comment]
Hi, I'm interested in using a ps3joy in USB mode as well

**Comment by mikaelarguedas** [comment]
This can be done by using the standard "joy" package.
You need to have the ps3 controller connected to your machine and hold the PS button for a couple seconds. It is then recognized as a regular Linux joystick and the "joy" node works to detect event and populate messages accordingly
