### ISSUE TITLE
Run ROS joy with PS4 controller and Jetson tx2

### ISSUE THREAD

**Issue by ArtlyStyles** [ros-drivers/joystick_drivers#143]
Can I run this package with PS4 controller on Jetson tx2? Could anyone point me some information about how to pair PS4 controller and TX2 and how to setup?

**Comment by JWhitleyAStuff** [comment]
@ArtlyStyles You can use this repo on a Jetson TX2 (you may have to build it from source there) but we have seen button mapping issues between the TX2 and other platforms so make sure you know which buttons map to which indices in the `sensor_msgs/Joy` message. As for information on pairing the controller to a TX2, you'll have much better luck asking at http://answers.ros.org/.
