### ISSUE TITLE
Melodic Patch Release

### ISSUE THREAD

**Issue by moriarty** [ros-drivers/joystick_drivers#144]
Could we get an updated release for Melodic?

There is a PS4 configuration file which is in the current source branch, but not yet in the any released version.

We’d like to depend on the Debian package, and have the PS4 config files.

See: https://github.com/fetchrobotics/fetch_robots/pull/45 for more information.

**Comment by JWhitleyAStuff** [comment]
Release: INCOMING

1.13.0 released to ros-shadow-fixed for `kinetic` and `melodic`. Watch https://discourse.ros.org/tags/release for package sync.

**Comment by moriarty** [comment]
Heads up @erelson

**Comment by moriarty** [comment]
Thanks! @JWhitleyAStuff

**Comment by erelson** [comment]
Thanks @JWhitleyAStuff !
