### ISSUE TITLE
Xbox controller inconsistent axis information

### ISSUE THREAD

**Issue by m-talha** [ros-drivers/joystick_drivers#145]
Hi,

I am relatively new to ROS and have encountered the same issue as #91 and #137. I read in #98 that the issue has been fixed but I am having trouble implementing the solution as it is not in the documentation. 

Where do I need to set the parameter `default_trig_val` as I tried to set it in the command line with `rosrun joy joy_node dev:=/dev/input/js3 _default_trig_val:=true` and it has not worked.

Thanks

**Comment by JWhitleyAStuff** [comment]
Very sorry this hasn't been handled recently. Actually, it's been determined that #98 did not fix this issue. I will be doing some reorganization of this whole repo soon so I will add this to my list to fix. Thanks.
