### ISSUE TITLE
 Couldn't open joystick force feedback!

### ISSUE THREAD

**Issue by mshong0320** [ros-drivers/joystick_drivers#146]
Trying to run the joy_node with logitech joystick controller on Kinetic version Ubuntu 16.04, but it's giving me an error [ERROR] [1561675023.851541705]: Couldn't open joystick force feedback!
Tried with multiple joy sticks and i can't figure out what's causing this and how to fix it.

**Comment by JWhitleyAStuff** [comment]
This is just a warning. It is letting you know that force feedback is not available on the joystick that you are using. It does not affect normal use of the controller.

**Comment by basvroeg** [comment]
if it's just warning, then also display it as a warning instead of an error please...

this tends to get confusing quickly!

**Comment by nathangeorge1** [comment]
If possible, you can change ROS_ERROR to ROS_WARN if this is the case.

**Comment by JWhitleyAStuff** [comment]
@nathangeorge1 / @basvroeg - PRs are welcome!

**Comment by aaronaaronson98** [comment]
I just re-found this in my testing of the ros2 branch. I'm not sure how the PR process works on this repo (first timer!) but would this help?

https://github.com/ros-drivers/joystick_drivers/pull/189
