### ISSUE TITLE
Discrete jumps to maximum values on xbox360 triggers

### ISSUE THREAD

**Issue by GrantDare** [ros-drivers/joystick_drivers#147]
Hi team,

I am using the joy node to interpret a clone xbox360 controller. I am experiencing discrete jumps to maximum intermittently when slowly depressing the triggers. That is that 1 is fully released and -1 is fully pressed. I don't have terminal readouts with me atm however, I have written down the numbers in the messages that follow the issue. Rounded to two decimal places, they are:
```
1
1
-0.96
-0.99
-0.98
-0.97
1
0.98
0.97
0.5
```

This is when attempting to depress to around 25% of the trigger slowly (0.5). Is this a known issue or can you confirm the problem is external to joy? If so, do you have any suggestions to rectify the issue id it is external to joy?

**Comment by JWhitleyAStuff** [comment]
I can not confirm for sure but this is likely a dead-zone issue on the triggers. It definitely isn't something that's in the code.
