### ISSUE TITLE
fatal error: cwiid.h: No such file or directory

### ISSUE THREAD

**Issue by Tengyun-Mo** [ros-drivers/joystick_drivers#148]
I got this error when I make the project. How to fix it?Do you have any suggestion?I'm very appreciate it.

**Comment by Tengyun-Mo** [comment]
I have solved this problem .My solution is as follows:
**step1:**
`$ git clone https://github.com/abstrakraft/cwiid/tree/master`
**step2:**
```
$ cd cwiid
$ aclocal
$ autoconf
$ ./configure
$ make
$ sudo make install
```

**Comment by JWhitleyAStuff** [comment]
@zhangying - This is also available as an Ubuntu package https://packages.ubuntu.com/bionic/libcwiid-dev. Using `rosdep` to install the dependencies for this package would also install it.
