### ISSUE TITLE
How to pair ps3 on TX2?

### ISSUE THREAD

**Issue by Tengyun-Mo** [ros-drivers/joystick_drivers#149]
I have a bluetooth adapters named CSR4.0 .The node didn't work when I paired PS3.

**Comment by Tengyun-Mo** [comment]
My system is ubuntu18.04

**Comment by Tengyun-Mo** [comment]
I can't found ps3 via device search.I don't where the problem is?Who can help me?I'm very appreciate it.

**Comment by LazyEngineerToBe** [comment]
Can you see the device when you run `lsusb` ?

**Comment by Tengyun-Mo** [comment]
Thanks for your response.Yes,I can see the device when I run lsusb.The bluetooth adapter can find other device like wireless keyboard,but it can not find ps3.

**Comment by LazyEngineerToBe** [comment]
If you can't see the device listed in the terminal, then it's a hardware issue. Unrelated to ROS. Are you sure your controller is compatible with Bluetooth? It might be using a different RF protocol.

**Comment by Tengyun-Mo** [comment]
Thanks,I changed another buletooth adapter,and it worked well.Thank you again
