### ISSUE TITLE
steering wheel logitech g920 with ubutnu 16.04

### ISSUE THREAD

**Issue by takanotume24** [ros-drivers/joystick_drivers#150]
Hello.
I would like to use the g920(not g29) steering controller, is this node compatible?
I look forward to hearing from you.
(g920:for xbox one or windows, g29:for ps4 and windows)

**Comment by takanotume24** [comment]
I found a solution.
After setting "UDEV and usb_modeswitch" according to this site([BURNING MIDNIGHTm.at.work: Logitech G920 Steering Wheel on Linux - Ubuntu 16.04, Linux Mint 18](http://burning-midnight.blogspot.com/2017/11/logitech-g920-steering-wheel-on-linux.html)), and when I executed 
```
$ roscore
$ rosrun joy joy_node
```
I got "/ joy".
Thank you.

**Comment by JWhitleyAStuff** [comment]
Glad you got it working! Thanks for providing the solution.
