### ISSUE TITLE
Operate two spacenav's on the same machine  (ros-pkg ticket #3832)

### ISSUE THREAD

**Issue by wjwwood** [ros-drivers/joystick_drivers#16]
Could you make it so we can bring up multiple spacenav devices on a single machine?

trac data:
- Owner: **blaise**
- Reporter: **sglaser**
- Reported at: **Wed Feb 17 19:03:21 2010**
- URL: https://code.ros.org/trac/ros-pkg/joystick_drivers/ticket/3832

**Comment by tobiascz** [comment]
Are there any updates/workarounds available? The issue comes probably due to the library because it only creates one socket file which will be used even if there are two mice plugged in right?
