### ISSUE TITLE
ROS 2: Reenable diagnostics in joy_linux

### ISSUE THREAD

**Issue by clalancette** [ros-drivers/joystick_drivers#164]
The port of joy_linux was done back in a time before diagnostics existing in ROS 2.  Now that it exists, we should spend some time and re-enable diagnostics there.

**Comment by blacksoul000** [comment]
any news here?

**Comment by clalancette** [comment]
I'm probably not going to have time to work on this in the near future.  But if you'd like to contribute a pull request to re-enable it, I'd be happy to review.

**Comment by blacksoul000** [comment]
@clalancette, Done. #181

**Comment by blacksoul000** [comment]
#182

**Comment by JWhitleyWork** [comment]
Closed by #181 and #183.
