### ISSUE TITLE
joy_node running on windows produces different /joy output compared to ubuntu with Logitech F710

### ISSUE THREAD

**Issue by altineller** [ros-drivers/joystick_drivers#176]
Hello,

I installed ROS on windows 10, and one of the first things I tried to get working was the joystick. 

After running joy_node with the provided launch file, I get the following on rostopic echo /joy

`C:\Users\can>header:
  seq: 469
  stamp:
    secs: 1594565425
    nsecs: 207101300
  frame_id: ''
axes: [0.0, 0.0]
buttons: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]`

-

The joystick f710 usually shows more axes than this. Just the left stick is captured and put in axes, but not the right stick, also z-axis is missing.

The provided launch file looks like this

`<?xml version="1.0"?>
<launch>
    <node pkg="joy" type="joy_node" name="joy" output="screen">
        <param name="mappings" type="string" value="$(find joy)/launch/gamecontrollerdb.txt" />
    </node>
</launch>`

In the gamecontrollerdb.txt file I just have one line:

`6d0419c2000000000000504944564944,Logitech F710 Gamepad,a:b1,b:b2,back:b8,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,leftshoulder:b4,leftstick:b10,lefttrigger:b6,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b11,righttrigger:b7,rightx:a2,righty:a3,start:b9,x:b0,y:b3,platform:Windows
`

I apologize if I am posting this issue to a wrong repository. The package.xml file pointed out to this adress, but upon inspecting your code, I could not really find any windows related parts in it.

Best Regards,
C.

**Comment by JWhitleyWork** [comment]
@altineller The best place for troubleshooting advice is going to be on [ROS Answers](https://answers.ros.org). Make sure you mention what version of WSL you're running, how you installed the ROS package (from source or package repo), what version of the package, and as many details as you can about your environment.
