### ISSUE TITLE
Spacenav pro segfault

### ISSUE THREAD

**Issue by ViaudJV** [ros-drivers/joystick_drivers#190]
Hi,
i work with ros-melodic and a spacenav pro.
It's Spacenav with 14 buttons.
When i try to use the other buttons than menu an fit the node crash.
I find the problem!
 it's because in spacenav_node.cpp line 207

 case SPNAV_EVENT_BUTTON:
	joystick_msg.buttons[sev.button.bnum] = sev.button.press;
        joy_stale = true;
        break;

sev.button.bnum can have a value up to 26 and joystick_msg.buttons size  is 2.
I resolve this problem in increase the size of sev.button.bnum from 2 to 26 (line 142)

**Comment by JWhitleyWork** [comment]
Great! Would you mind creating a pull request?

**Comment by ViaudJV** [comment]
Done
