### ISSUE TITLE
joy_node uses a lot of CPU when no joystick is connected

### ISSUE THREAD

**Issue by tonynajjar** [ros-drivers/joystick_drivers#246]
We have joy_node always running but the joystick is only connected in need to teleop the robot. I noticed that when it is not connected and the node is launched, it uses a lot of CPU. I tracked down the high CPU consumption to this [line](https://github.com/ros-drivers/joystick_drivers/blob/ros2/joy/src/joy.cpp#L479).

Why do we we need to call SDL_Quit in this loop? Is there a better way to avoid the high CPU consumption?

**Comment by tonynajjar** [comment]
Also, we noticed that this is not a problem on galactic and given that the joy_node barely changed between galactic in Humble, maybe SDL changed

**Comment by doisyg** [comment]
Noticing the same on  `Humble`

**Comment by tonynajjar** [comment]
Can you check if the linked PR fixes it for you @doisyg

**Comment by doisyg** [comment]
Sorry for the late answer @tonynajjar, confirming your PR fixes the issue for me

**Comment by JWhitleyWork** [comment]
Fixed by #247 .

**Comment by doisyg** [comment]
Can we release it also ? 🙏

**Comment by JWhitleyWork** [comment]
> Can we release it also ? pray

Working on it. I'm currently missing some required access. See https://github.com/ros2-gbp/joystick_drivers-release/issues/9 for details.
