### ISSUE TITLE
Is this package allow to send cmd to control the joystick (steering wheel) to spin?

### ISSUE THREAD

**Issue by TZECHIN6** [ros-drivers/joystick_drivers#256]
I am very new to useing HID with ros, I found quite a lot of people using this joy topics to read the controller input, and yes, I can repeat this on my project as well.

However, what if I want to turn the way round, read the input from the software, and send cmd (e.g. force feedback) to steer the wheel, is it possible for this package? Thanks everyone!

**Comment by JWhitleyWork** [comment]
@TZECHIN6 Unfortunately, that is not something that the node currently supports. If you would like to add support, you can investigate the API for doing so and add the feature in a Pull Request.
