### ISSUE TITLE
auto repeat not encforced if movement is in deadzone limit or when no change in joystick state

### ISSUE THREAD

**Issue by yegarti** [ros-drivers/joystick_drivers#260]
ROS2 Humble  - 3.2.0 humble-devel

When a movement is detected there is no check if auto repeat is needed, but the movement may be filtered because it's inside the deadzone.
In that case there will be no auto repeat check but also no publish of a new message.

When working with my controller, the joystick is always in the deadzone and that causes the node to stop outputting any messages even when auto repeat is on.

Fixed by replacing  the `else` in
https://github.com/ros-drivers/joystick_drivers/blob/09082e3567f147b9721c401fba74d42eb9847636/joy/src/joy.cpp#L453
with 
`if (!success || !should_publish) {`

EDIT:
Another place where this might happen is when there is no change in the joy axis values:
https://github.com/ros-drivers/joystick_drivers/blob/09082e3567f147b9721c401fba74d42eb9847636/joy/src/joy.cpp#L195-L197
skipping this 'if' means that the message won't be published

**Comment by clalancette** [comment]
This should be fixed with #261 now, so closing this out.
