### ISSUE TITLE
spacenav for ROS2 humble

### ISSUE THREAD

**Issue by kamiradi** [ros-drivers/joystick_drivers#285]
Hi,

Thanks for the great work.

I was wondering if the spacenav drivers for ROS2 humble were being maintained on this repository? If not, can you point me towards where these drivers may exist.

Thank you for the information.

**Comment by clalancette** [comment]
Yes, they are here: https://github.com/ros-drivers/joystick_drivers/tree/main/spacenav_node

Please open questions like this on https://robotics.stackexchange.com/questions/tagged/ros, which is our central Question and Answer site.  You'll get a better answer there, and it will be searchable for the future.

Make sure to include a lot of information on what platform you are using, which ROS distribution you are using, and the exact steps you took.
