### ISSUE TITLE
Ros2 Joy Package Doesnt Work w/ WSL2 and USBIP

### ISSUE THREAD

**Issue by falOn-Dev** [ros-drivers/joystick_drivers#286]
Exactly what it sounds like, when using wsl2 and usbip to passthrough my xbox controller, it appears when running `lsusb` but doesnt appear when running ` ros2 run joy joy_enumerate_devices`

**Comment by clalancette** [comment]
I don't have any experience with WSL2, so I'm not sure what is happening.  One thing you could try is to run "joy_linux" instead; that uses a slightly different mechanism to find joystick devices.  Does that work any better for you?

**Comment by falOn-Dev** [comment]
joy_linux worked, thank you!
