### ISSUE TITLE
ps3joy system daemon stops responding on PR2  (ros-pkg ticket #5121)

### ISSUE THREAD

**Issue by wjwwood** [ros-drivers/joystick_drivers#38]
I've had two occurrences now where teleop_joystick doesn't respond to input until I login to c2 and restart the py3joy system daemon. No obvious error or warning messages in /var/log/ps3joy.log

I am running the version of ps3joy from electric (I think most robots run the version from diamondback).

trac data:
- Owner: **mwise**
- Reporter: **ahendrix**
- Reported at: **Fri Aug 12 13:42:22 2011**
- URL: https://code.ros.org/trac/ros-pkg/joystick_drivers/ticket/5121

**Comment by JWhitleyAStuff** [comment]
Outdated.
