### ISSUE TITLE
ps3joy*.py kills itself if not root, even if user has access to device

### ISSUE THREAD

**Issue by Lopako** [ros-drivers/joystick_drivers#53]
In ps3joy.py and ps3joy_node.py [[https://github.com/ros-drivers/joystick_drivers/blob/groovy-devel/ps3joy/scripts/ps3joy_node.py#L566-L568]]
, the start of the script blindly checks if not root user and then quits if anything else, even if current user has permissions to access the device.  It should check if the current user's actual access is fine, or at the very least, provide an override option to allow running as non-root.

Related to #51 and comments.

**Comment by JWhitleyAStuff** [comment]
Closing due to lack of response.
