### ISSUE TITLE
Jade Release

### ISSUE THREAD

**Issue by wjwwood** [ros-drivers/joystick_drivers#72]
I wanted to go ahead and start the Jade discussion here, since we are probably not going to import `qtsixa` for Utopic and Vivid, see: https://github.com/ros/rosdistro/issues/6435#issuecomment-70165912

Is this going to be an issue or has this package moved on from using `qtsixa`? The only reason it is on our radar is that we were importing it for other Ubuntu distros in the past.

**Comment by mikeferguson** [comment]
Nothing in this repo requires qtsixa -- qtsixa was basically an alternative to ps3joy.

**Comment by vrabaud** [comment]
so we're all good then ? @jbohren , should we release for Jade ? I can if you want, using the indigo-devel banch.

**Comment by mikeferguson** [comment]
@vrabaud I actually released this into indigo, so I'll go ahead and push a jade release in a few minutes.

**Comment by vrabaud** [comment]
thx ! I saw there were commits after 1.10, not sure they are critical though: https://github.com/ros-drivers/joystick_drivers/commits/indigo-devel

**Comment by mikeferguson** [comment]
yeah -- I'm tagging a new release right now -- mainly for the fedora guys

**Comment by mikeferguson** [comment]
https://github.com/ros/rosdistro/pull/8542
