### ISSUE TITLE
Memory corruption for SpaceMouse Pro

### ISSUE THREAD

**Issue by jpetereit** [ros-drivers/joystick_drivers#80]
The _3Dconnexion SpaceMouse Pro_ has 15 buttons. It generates messages with button IDs ranging from 0 to 26. However, the `buttons` array of the `Joy` message is statically resized to 2, which leads to memory corruption when setting button IDs larger than 1 in [line 148](https://github.com/ros-drivers/joystick_drivers/blob/4a9959291c36b2d5ba1b90cebb9633c8ddd35f58/spacenav_node/src/spacenav_node.cpp#L148).

The easiest fix is to always [resize the button array](https://github.com/ros-drivers/joystick_drivers/blob/4a9959291c36b2d5ba1b90cebb9633c8ddd35f58/spacenav_node/src/spacenav_node.cpp#L87) to 27, but maybe there is a more elegant way to determine the actual type or button count of the connected device.

**Comment by JWhitleyAStuff** [comment]
Closing due to this issue being very old.
