### ISSUE TITLE
Wiimote_node Performance on resource constrained systems

### ISSUE THREAD

**Issue by mdhorn** [ros-drivers/joystick_drivers#85]
I've been using the Wiimote package for manually controlling a couple of robots which are running on constrained, embedded system. The performance for Python in general isn't that great on these platforms which results in the Wiimote node consuming about 25% of the CPU resources.

To meet the performance I needed, did a rewrite of the Wiimote node in C++ using the existing Python node as the requirements. Using C++ cut the memory consumption by 50-60%, and the reduced the number of cpu-clock cycles used significantly; 20x-30x depending upon the use case.

![image](https://cloud.githubusercontent.com/assets/12535259/12625462/cc005404-c4e8-11e5-9ec2-b6afe2d65aab.png)

I'd like to contribute this C++ version upstream and hopefully it will be useful to others.

Currently integrating my C++ code into the existing repo to ensure it can coexist with the Python version.

For validation, i have been comparing the published data for various use cases between the Python and C++ versions, using the node for controlling a few different bots, and verify the calibration process. Is there any other validation or test suite I should be using?

On a related topic, I created a fairly generic teleop_wiimote node for controlling a few bots I've been testing. You can using the D-pad on the Wiimote or the Nunchuk for velocity control. It may not be perfect for all use cases, but at a minimum it provides a starting point for anyone wanting to customize it more.
Would it be reasonable to include a 'teleop_wiimote' node in the wiimote package? Or should it be upstreamed to https://github.com/ros-drivers/joystick_drivers_tutorials ?

Thank you for your consideration.

**Comment by JWhitleyAStuff** [comment]
Fix was implemented in #87. Closing.
