### ISSUE TITLE
Lunar release please?

### ISSUE THREAD

**Issue by bmagyar** [ros-drivers/joystick_drivers#99]
Hi @mdhorn,

Could we get a Lunar release please? Is there something blocking it?

**Comment by BrunoXL** [comment]
According to ros status page (http://repositories.ros.org/status_page/blocked_releases_lunar.html?q=joy&s=6&r=1) alll dependencies have been releases.
I'm also interested in a Lunar release.

**Comment by mikaelarguedas** [comment]
:+1: that would be great to have this package available in Lunar

**Comment by mikaelarguedas** [comment]
@jbohren Any update on this ? (I see that all PRs have been merged :smiley:)

**Comment by mikaelarguedas** [comment]
@jprod123 Is there anything we can do to help getting this released? this is currently the repository [blocking the most packages](http://repositories.ros.org/status_page/blocked_releases_lunar.html?s=6&r=1) from being released into lunar

**Comment by mikaelarguedas** [comment]
@jbohren @jprod123 FYI I'm planning on releasing the current kinetic version (1.11.0-0) into Lunar tomorrow.
Please comment here if there is a reason not to do so.

**Comment by brleme** [comment]
@mikaelarguedas , did you work on it?

**Comment by mikaelarguedas** [comment]
@brleme Yes, I added the missing rosdep keys. One PR is [pending](https://github.com/ros/rosdistro/pull/15808), once it's merged I'll make the release

**Comment by mikaelarguedas** [comment]
released in https://github.com/ros/rosdistro/pull/15813

**Comment by cdancette** [comment]
Is the package including joy is in the ubuntu repos already ? 
How can we use joy in the meantime if it's not ?

**Comment by mikaelarguedas** [comment]
The package is in the testing repository for now and will be available in the main repository at the next sync (we try to sync every 2-3 weeks). A good way to track the status of a ROS package is to look at the ROS status pages (e.g. http://repositories.ros.org/status_page/ros_lunar_default.html?q=joy).

To be able to use it there are a few options:
-  [add the testing repository to your sources](http://wiki.ros.org/ShadowRepository) and you will be able to run `sudo apt update && sudo apt install ros-lunar-joy`. 
- wait for the next sync (announced on discourse.ros.org, [example here](https://discourse.ros.org/t/new-packages-for-lunar-2017-08-22/2490)).
- clone this repository and build the packages from source

Hope this helps
